### ISSUE TITLE
Salam. Website down

### ISSUE THREAD

**Issue by iqfareez** [asdacap/iiumschedule#4]
https://iiumschedule.asdacap.com/schedulemaker/
![image](https://user-images.githubusercontent.com/60868965/103257232-4fbe6a80-49cb-11eb-890d-5f7c8b4d1168.png)

**Comment by asdacap** [comment]
Fixed

**Comment by iqfareez** [comment]
Thank you. Closing.

**Comment by MohammadShahdad** [comment]
Website down again.

**Comment by asdacap** [comment]
Recycled server. Should be up.

**Comment by iqfareez** [comment]
Thank youu
