### ISSUE TITLE
Cannot save & print

### ISSUE THREAD

**Issue by iqfareez** [asdacap/iiumschedule#9]
This page shows after clicking save. Not loading anything.

![image](https://user-images.githubusercontent.com/60868965/157356287-ffe361c5-50ca-4379-9a8a-a378fc5147ac.png)

**Comment by asdacap** [comment]
Hi, if you inspect elements, what does it say?

**Comment by iqfareez** [comment]
Mixed content error

```
?ctoken=ppwbt58sp1qww5ezalxp:76 Mixed Content: The page at 'https://iiumschedule.asdacap.com/scheduleloader/?ctoken=ppwbt58sp1qww5ezalxp' was loaded over HTTPS, but requested an insecure script 'http://www.google-analytics.com/ga.js'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ ?ctoken=ppwbt58sp1qww5ezalxp:76

iiumschedule.asdacap.com/:154 Mixed Content: The page at 'https://iiumschedule.asdacap.com/scheduleloader/?ctoken=ppwbt58sp1qww5ezalxp' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://iiumschedule.asdacap.com/scheduleloader/?ctoken=ppwbt58sp1qww5ezalxp&test=1'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by asdacap** [comment]
What about the network tab?

**Comment by iqfareez** [comment]
![image](https://user-images.githubusercontent.com/60868965/158041911-5cb2f087-fc35-4e47-b022-e6c2035b737a.png)

Some kind of cors error from Google Analytics script?

**Comment by iqfareez** [comment]
301
![image](https://user-images.githubusercontent.com/60868965/158041953-56703c3a-4848-455b-a1a5-0ac474d9390f.png)

302
![image](https://user-images.githubusercontent.com/60868965/158041958-acfa2b05-71f0-48bf-93e9-237e0b5deabc.png)

**Comment by asdacap** [comment]
Should be fixed.

**Comment by iqfareez** [comment]
Tqsm!!
